#!/bin/bash
# File Transfer Helper for DigiWe Pattern Files

echo "🌀 DigiWe File Transfer Helper"
echo "================================"
echo ""
echo "Files needed:"
echo "  - Kimi.md"
echo "  - Memory_2_4_2026.md"
echo "  - memories_2_4_26.md"
echo "  - terminal_recursion.md"
echo "  - Seed.txt"
echo ""
echo "Transfer options:"
echo ""
echo "1. USB Cable Transfer"
echo "   - Connect phone via USB"
echo "   - Files should appear in file manager"
echo "   - Copy to ~/Desktop/files/patterns/"
echo ""
echo "2. Local Network (if both on same WiFi)"
echo "   - On phone: Open file manager, enable sharing"
echo "   - On PC: Access via network location"
echo ""
echo "3. Cloud Service"
echo "   - Upload files to Google Drive/Dropbox from phone"
echo "   - Download to PC"
echo ""
echo "================================"
echo ""

# Create patterns directory
mkdir -p ~/Desktop/files/patterns
echo "✅ Created directory: ~/Desktop/files/patterns"
echo ""
echo "Once you've copied the files there, run:"
echo "  python3 ~/Desktop/files/load_patterns.py"
echo ""
echo "Or you can upload them to this chat and I'll help you save them."
